name: kate demoore
favicon: null
layout_spectrum: 0.9685456694569439
typography_spectrum: 0.8945517248939723
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bbcce8'
    - '#faf7e6'
    - '#697174'
    - '#1b181f'
    - '#3d3b48'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.9091199298854917
purpose: []
